export const STATUS_TYPE = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
};

export const FORM_TYPE = {
  CHANGE_INPUT: "CHANGE_INPUT",
  ADD_TAG: "ADD_TAG",
  REMOVE_TAG: "REMOVE_TAG",
  INCREASE: "INCREASE",
  DECREASE: "DECREASE",
};
